{{- $name := required "secret.name is required" .Values.secret.name -}}
{{- if and .Values.secret .Values.secret.create }}
{{- $host := required "secret.host is required if secret.create is true" .Values.secret.host -}}
{{- $port := required "secret.port is required if secret.create is true" .Values.secret.port -}}
{{- $database := required "secret.database is required if secret.create is true" .Values.secret.database -}}
{{- $username := required "secret.username is required if secret.create is true" .Values.secret.username -}}
{{- $password := required "secret.password is required if secret.create is true" .Values.secret.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "db2-schema.labels" . | nindent 4 }}
stringData:
  {{ default "host" .Values.secret.host_key }}: {{ $host }}
  {{ default "port" .Values.secret.port_key }}: {{ $port | quote }}
  {{ default "database" .Values.secret.database_key }}: {{ $database }}
  {{ default "username" .Values.secret.username_key }}: {{ $username }}
  {{ default "password" .Values.secret.password_key }}: {{ $password }}
{{- end }}
