{{- $name := required "secret.name is required" .Values.secret.name -}}
{{- if and .Values.secret .Values.secret.create }}
{{- $host := required "secret.host is required if secret.create is true" .Values.secret.host -}}
{{- $port := required "secret.port is required if secret.create is true" .Values.secret.port -}}
{{- $database := required "secret.database is required if secret.create is true" .Values.secret.database -}}
{{- $username := required "secret.username is required if secret.create is true" .Values.secret.username -}}
{{- $password := required "secret.password is required if secret.create is true" .Values.secret.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "db2-schema.labels" . | nindent 4 }}
stringData:
  host: {{ $host }}
  port: {{ $port | quote }}
  database: {{ $database }}
  username: {{ $username }}
  password: {{ $password }}
{{- end }}
