apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ConfigmapName }}
  labels:
    app: cp-db2schema
data:
  cp_imageentrypoint.sh: |
    #!/bin/sh
    chmod -R 777 /database/
    mkdir -m  777 /var/custom
    cp /db2schemascripts/cp_db2schema_setup.sh /var/custom 
    cp /db2schemascripts/cp_addusers_setup.sh /var/custom 
    sed -i '205,209d;' /var/db2_setup/lib/setup_db2_instance.sh
    /var/db2_setup/lib/setup_db2_instance.sh
    ls -l /var/custom
    #chown -v db2inst1 /var/custom/cp_db2schema_setup.sh
    #/var/custom/cp_addusers_setup.sh
    #/var/custom/cp_db2schema_setup.sh
    id
    #chmod a+x /var/custom/cp_db2schema_setup.sh
    #sleep 600


  cp_addusers_setup.sh: |
    #!/bin/sh -x
    id
    ############################################################
    # Adding DB2 users
    ############################################################
    useradd -NM -d / -f -1 -s /sbin/nologin -K UID_MIN=2000 omdb && echo omdb:omdb | chpasswd omdb
    useradd -NM -d / -f -1 -s /sbin/nologin -K UID_MIN=2000 omdb_stat && echo omdb_stat:omdb_stat |  chpasswd omdb_stat
    useradd -NM -d / -f -1 -s /sbin/nologin -K UID_MIN=2000 omdb_tran && echo omdb_tran:omdb_tran |  chpasswd omdb_tran
    useradd -NM -d / -f -1 -s /sbin/nologin -K UID_MIN=2000 omdb_mstr && echo omdb_mstr:omdb_mstr |  chpasswd omdb_mstr
    useradd -NM -d / -f -1 -s /sbin/nologin -K UID_MIN=2000 omdb_conf && echo omdb_conf:omdb_conf |  chpasswd omdb_conf

  cp_db2schema_setup.sh: |
    #!/bin/sh -x
    #id
    #sleep 60
    #id
    #. /home/config/db2inst1/sqllib/db2profile
    # ./database/config/db2inst1/sqllib/db2profile
    # . /mnt/blumeta0/home/db2inst1/sqllib/db2profile
    #su - db2inst1
    # id
    #uselvl -d /database/config/db2inst1/sqllib/db2profile
    
    ############################################################
    #  Create DB2 Schema
    ############################################################
    
    # ./database/config/db2inst1/sqllib/db2profile
    #. $HOME/sqllib/db2profile
    #db2start
    su - db2inst1 -c 'db2 catalog tcpip node prvsndb2 remote "'"${DB2Host}"'" server "'"${db2_port}"'"; 
    db2 catalog db NAME as "'"${database_name}"'" at node prvsndb2;
    db2 connect to "'"${database_name}"'" user db2inst1 using "'"${DB2INST1_PASSWORD}"'";
    db2 create schema omdb;
    db2 create schema omdb_conf;
    db2 create schema omdb_mstr;
    db2 create schema omdb_tran;
    db2 create schema omdb_stat;
    db2 grant dbadm on database to user omdb;
    db2 grant dbadm on database to user omdb_conf;
    db2 grant dbadm on database to user omdb_stat;
    db2 grant dbadm on database to user omdb_tran;
    db2 grant dbadm on database to user omdb_mstr;' 
    exit
    #db2stop
    #db2start
    #db2
    