apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.jobName }}
  #label:
    #app: db2schema
spec:
  template:
    metadata:
      name: db2schema-setup-pod
      annotations:
        checksum/config-map: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: db2user
      restartPolicy: Never
                 
        
      containers:
        - name: cp-database-container
          #image: icr.io/db2u/db2u.tools@sha256:c7662c7d63f4e1b9166e27ba60878bd7d8027ac42fc4cbec2dea3d54cb82abc8
          image: ibmcom/db2
          ports:
            - containerPort: 50000
          volumeMounts:
            - mountPath: /db2schemascripts
              name: db2schemascripts   
          env:
            - name: LICENSE
              value: "accept"
            - name: CPDClusterHost
              value:  {{ .Values.CPDClusterHost }}
            - name:  db2_ssl_port
              value: {{ .Values.db2_ssl_port | quote }}
            - name:  dbuser
              value: {{ .Values.dbuser }}
            - name:  database_name
              value: {{ .Values.database_name }}
            - name: DB2INST1_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db2inst1-user-credentials
                  key: db2inst1_password
          #securityContext:
            #capabilities:
              #drop:
                #- KILL
                #- SETUID
                #- SETGID
                #- MKNOD
                #- ALL
            #runAsUser: 1000
            #allowPrivilegeEscalation: false
          command:
            - /bin/sh
          args:
            - -c
            - /db2schemascripts/cp_imageentrypoint.sh 
      volumes:
        - name: db2schemascripts
          configMap:
            name: {{ .Values.ConfigmapName }}
            defaultMode: 0777
        
        